name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift 6.1
        uses: fwal/setup-swift@v2
        with:
          swift-version: "6.1"

      - name: Build package for distribution
        run: swift build --configuration release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          
# Command to create new release:
# git tag v*.*.*
# git push origin v*.*.*